#!/bin/bash
cd /usr/src
for X in linux-* ; do
	test -e "$X/Makefile" && continue
	rm -rf -- "$X"
done

for X in /boot/vmlinuz-* ; do
	test -e "$X" || continue
	grep -q ".old$" <<< "$X" && continue
	KERNELVER="${X#*-}"
	test -d "/usr/src/linux-${KERNELVER}" && continue
	rm -i -- /boot/{vmlinuz,config,initramfs,System.map}-"${KERNELVER}"* && \
	rm -rf -- /lib/modules/"${KERNELVER}"
	true
done
